markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Homepage:
      - index.md
  - Announcements:
      - blog/index.md
plugins:
  - blog
  - search
site_name: Ankeny Northview PTO
site_url: https://ptonorthview.org
theme:
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.follow
  name: material
  palette:
    primary: blue grey
